# <b>Python DA Assignment 1:  Data Analysis using NumPy and Pandas </b>

### <b> <span style="color:darkblue">Numpy Array Operations:</span> </b>

<b> <span style="color:purple">1. Create a 1D NumPy Array: </span></b>

<b>Create a 1D NumPy array named temperatures_w1 for Week 1 with the following values:</b>

[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

In [2]:
import numpy as np

In [3]:
temperatures_w1=np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

<span style="color:green"><b>Numpy is imported for creating array.</b></span>

<span style="color:green"><b>The np.array() function creates a one-dimensional array "temperatures_w1"</b></span>

<span style="color:purple"><b>2. Inspection and Properties: </b></span>

 <b>Inspect the shape, data type, and the number of elements in the array. 
Inspect the shape of the temperatures_w1 array.</b>

In [4]:
temperatures_w1.shape

(7,)

<span style="color:green"><b>temperatures_w1 is a one dimensional array with 1 row and 7 columns.</b></span>

In [5]:
temperatures_w1.dtype

dtype('float64')

In [6]:
temperatures_w1.size

7

<span style="color:green"><b>.size returns the total number of values in the array.Here array contains 7 elements.</b></span>

<span style="color:purple"><b>3. Array Operations: </b></span>

<b>● Convert the temperatures_w1 from Celsius to Fahrenheit using the formula: Fahrenheit = (Celsius * 9/5) + 32 </b>

In [7]:
temperatures_f=(temperatures_w1* 9/5) + 32
print(temperatures_f)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

<span style="color:green"><b>The formula converts Celsius to Fahrenheit. NumPy performs the calculation on every element of the array.</b></span>

<b>● Find the maximum, minimum, and mean temperatures for the week.</b>

In [8]:
Max_temp=np.max(temperatures_w1)
Min_temp=np.min(temperatures_w1)
Mean_temp=np.mean(temperatures_w1)
print("Maximum temperature : ",Max_temp)
print("Minimum temperature : ",Min_temp)
print("Mean temperature : ",Mean_temp)

Maximum temperature :  26.1
Minimum temperature :  20.8
Mean temperature :  23.542857142857144

<span style="color:green"><b>np.max() finds the highest temperature,which is 26.1.</b></span>

<span style="color:green"><b>np.min() finds the lowest temperature, which is 20.8.</b></span>

<span style="color:green"><b>np.mean() calculates the average temperature, which is 23.54.</b></span>

<span style="color:purple"><b>4. Array Slicing and Indexing: </b></span>

<b>● Extract the temperatures for the first three days of the week.</b> 

<b>● Extract the temperatures for the weekend (last two days).</b>

<b>● Extract the temperatures for the middle three days of the week.</b>

In [9]:
print("Temperatures for the first three days of the week : ",temperatures_w1[0:3])
print("Temperatures for the weekend : ",temperatures_w1[-2:])
print("Temperatures for the middle three days of the week : ",temperatures_w1[2:5])

Temperatures for the first three days of the week :  [22.5 25.3 20.8]
Temperatures for the weekend :  [24.8 21.9]
Temperatures for the middle three days of the week :  [20.8 23.4 26.1]

<span style="color:purple"><b>5. Create a 2D Array: </b></span>

<b>Create a 2D NumPy array named temperatures where each row represents 
temperatures for a different week:</b> 

<b>★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1) </b>

<b>★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)</b>

In [10]:
temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

<span style="color:green"><b>The np.array() function creates a two-dimensional array "temperatures".It contains two rows,where the first row is Week 1 and the second row is Week 2.</b></span>

<span style="color:purple"><b>6. Inspect and Slice the 2D Array: </b></span>

<b>● Inspect and print the shape, data type, and total number of elements in the 
temperatures array.</b>

In [11]:
temperatures.shape

(2, 7)

<span style="color:green"><b>temperatures is a two dimensional array with 2 row and 7 columns.</b></span>

In [12]:
temperatures.dtype

dtype('float64')

In [13]:
temperatures.size

14

<span style="color:green"><b>.size returns the total number of values in the array.Here array contains 14 elements.</b></span>

<b>● Extract the temperatures for each week and the weekends (last two days) for both weeks.</b>

In [14]:
print("temperatures for each week 1 : ",temperatures[0])
print("temperatures for each week 2 : ",temperatures[1])

temperatures for each week 1 :  [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
temperatures for each week 2 :  [19.2 22.5 21.3 24.  23.5 22.8 20.1]

In [15]:
print("the weekends for week 1: ",temperatures[0,-2:])
print("the weekends for week 2: ",temperatures[1,-2:])

the weekends for week 1:  [24.8 21.9]
the weekends for week 2:  [22.8 20.1]

<span style="color:green"><b>The index [0] selects the first row and [1] selects the second row.</b></span>

<span style="color:green"><b>[0, -2:] selects the last two elements of the first row, and [1, -2:] selects the last two elements of the second row.</b></span>

### <b> <span style="color:darkblue">Pandas Series: </span> </b>

<b> <span style="color:purple">1. Creating Pandas Series:  </span></b>

<b>● Create a Pandas Series named marks with the following data:</b>

<b>➢ Marks: 95, 92, 89, 85, 80 </b>

<b>➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'</b>

In [16]:
import pandas as pd

In [17]:
Marks=pd.Series([95,92,89,85,80],index=['Rank1','Rank2','Rank3','Rank4','Rank5'])
print(Marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

<span style="color:green"><b>Pandas is imported for creating Series.</b></span>

<span style="color:green"><b>The pd.Series() function creates a Series named marks with five marks and custom indices.</b></span>

<b> <span style="color:purple">2. Indexing and Slicing:  </span></b>

<b>● Use the integer index position to access the mark of the 1st rank student. </b>

In [18]:
print("The mark of the 1st rank student : ",Marks.iloc[0])

The mark of the 1st rank student :  95

<span style="color:green"><b>iloc is used to acess the mark of 1st rank student.iloc accessor retrieves values using integer positions.</b></span>

<b>● Use the loc accessor to retrieve the marks of the top 3 ranks by 
specifying their index labels. </b>

In [19]:
print(Marks.loc['Rank1':'Rank3'])

Rank1    95
Rank2    92
Rank3    89
dtype: int64

<b><span style="color:green">The loc accessor selects values using their index labels.</span></b>

<b>● Use the iloc accessor to retrieve the mark of the 3rd rank student. </b>

In [20]:
print("The mark of the 3rd rank student : ",Marks.iloc[2])

The mark of the 3rd rank student :  89

<b>● Apply a boolean mask to filter the Series and retrieve the ranks where the 
marks are greater than 90. </b>

In [21]:
print(Marks[Marks>90])

Rank1    95
Rank2    92
dtype: int64

<span style="color:green"><b>A Boolean mask checks which marks are greater than 90.Rank1 and Rank2 has mark greater than 90.</b></span>

<b> <span style="color:purple">3. Manipulating Series:  </span></b>

<b>● Modify the mark of the student with the 1st rank to 100.</b>

In [22]:
Marks['Rank1']=100
print(Marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

<span style="color:green"><b>The statement marks['Rank1'] = 100 updates the mark associated with Rank1 from 95 to 100.</b></span>

<b>● Remove the entry corresponding to the last rank from the Series. </b>

In [23]:
Marks=Marks.drop(['Rank5'])
print(Marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

<span style="color:green"><b>The drop() method removes the entry with the index Rank5.</b></span>

<b>● Compute the CGPA by dividing each mark in the Series by 10.</b>

In [24]:
CGPA=Marks/10
print(CGPA)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

### <b> <span style="color:darkblue">Pandas DataFrame: </span> </b>

<b> <span style="color:purple">1. Creating Pandas DataFrame:  </span></b>

<b>● Create a Pandas DataFrame named transactions with the following data: </b>

<b>➢ TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110 </b>

<b>➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture', 
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'</b>

<b>➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 
'South', 'North' </b>

<b>➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400</b>

In [25]:
transactions = pd.DataFrame({"TransactionID":[101,102,103,104,105,106,107,108,109,110],
                             "ProductCategory":[ 'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
                             "Region":['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
                             "Amount":[200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
                            })

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

<span style="color:green"><b>The pd.DataFrame() function creates a DataFrame named transactions from a dictionary.</b></span>

<b> <span style="color:purple">2. Data Exploration: </span></b>

<b>● Display the transactions DataFrame and its basic information, including 
head, tail, shape, column names, and data types. </b>

In [26]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [27]:
transactions.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [28]:
transactions.tail()

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [29]:
transactions.shape

(10, 4)

In [30]:
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

In [31]:
transactions.dtypes

TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

In [32]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     str
 2   Region           10 non-null     str
 3   Amount           10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 593.0 bytes

<span style="color:green"><b>.head() displays the first five rows.</b></span>

<span style="color:green"><b>.tail() displays the last five rows.</b></span>

<span style="color:green"><b>.shape provides the shape of the dataframe. Here 10 rows 4 columns</b></span>

<span style="color:green"><b>.columns gives all columns from the dataframe</b></span>

<span style="color:green"><b>.dtypes displays the data type of each column.</b></span>

<b>● Display only the 'ProductCategory' and 'Amount' columns.  </b>

In [33]:
print(transactions[["ProductCategory","Amount"]])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

<span style="color:green"><b>Double square brackets are used to select multiple columns from a DataFrame.</b></span>

<b>● Retrieve the last 3 columns of the DataFrame using iloc or loc.</b>

In [34]:
print(transactions.iloc[:,-3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

<span style="color:green"><b>The iloc accessor selects data by integer position. The colon : selects all rows and -3: selects the last three columns.</b></span>

<b>● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.</b>

In [35]:
print(transactions[(transactions['Region']=='North')&(transactions['Amount']>200)])

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

<span style="color:green"><b>Boolean filtering selects rows that satisfy both conditions.<b></span>

<b>● Find the value counts for the 'ProductCategory' column. </b>

In [38]:
print(transactions.value_counts("ProductCategory"))

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

<span style="color:green"><b>The value_counts() method counts how many times each product category appears.</b></span>

<b>● Find the unique values in the 'Region' column. </b>

In [39]:
transactions["Region"].unique()

<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

<span style="color:green"><b>The unique() method returns the distinct values in the column Region.</b></span>

<b>● Group by 'Region' and find the mean amount for each region.</b>

In [40]:
transactions.groupby("Region")["Amount"].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

<span style="color:green"><b>The groupby() method groups transactions by region, and mean() calculates the average transaction amount for each region.</b></span>

<b> <span style="color:purple">3. Manipulating the DataFrame: </span></b>

<b>● Modify the 'Amount' for the transaction with TransactionID 102 to 165.</b>

In [43]:
transactions.loc[transactions["TransactionID"]==102,"Amount"]=165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

<span style="color:green"><b>The loc accessor selects the row where TransactionID is 102 and updates its Amount from 150 to 165.</b></span>

<b>● Add a new column 'Discount' by calculating 10% of the 'Amount'.</b>

In [50]:
transactions["Discount"]=transactions["Amount"]*10/100
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

<b>● Remove the row with TransactionID 109. </b>

In [51]:
transactions=transactions.drop(transactions[transactions["TransactionID"]==109].index)
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

<span style="color:green"><b>The .index finds the index of the identified row, and the drop() method removes that row from the DataFrame.</b></span>

<b>● Delete the 'Discount' column from the DataFrame.</b>

In [52]:
transactions.drop(columns=["Discount"],inplace=True)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400